let felveszBtn = document.querySelector('#felveszBtn'),
    form = document.querySelector('form'),
    Gyarto = form.Gyarto,
    ar = form.ar,
    modell = form.Model,
    Memoria = form.Memoria,
    Kamera = form.Kamera,
    leiras = form.leiras,
    leiras = form.leiras,
    OP = [
        { 'extra': 'IOS', 'ertek': form.IOS.checked },
        { 'extra': 'Android', 'ertek': form.Android.checked },
        { 'extra': 'Egyeb', 'ertek': form.Egyeb.checked },
        
    ],